/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRollupProcessor,
  IRollupProcessorInterface,
} from "../IRollupProcessor";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "interactionNonce",
        type: "uint256",
      },
    ],
    name: "receiveEthFromBridge",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IRollupProcessor__factory {
  static readonly abi = _abi;
  static createInterface(): IRollupProcessorInterface {
    return new utils.Interface(_abi) as IRollupProcessorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRollupProcessor {
    return new Contract(address, _abi, signerOrProvider) as IRollupProcessor;
  }
}
