/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISafeManager, ISafeManagerInterface } from "../ISafeManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "safe",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "deltaCollateral",
        type: "int256",
      },
      {
        internalType: "int256",
        name: "deltaDebt",
        type: "int256",
      },
    ],
    name: "modifySAFECollateralization",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "collateralType",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "usr",
        type: "address",
      },
    ],
    name: "openSAFE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_safeId",
        type: "uint256",
      },
    ],
    name: "safes",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "safe",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "dst",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wad",
        type: "uint256",
      },
    ],
    name: "transferCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "safe",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "dst",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "rad",
        type: "uint256",
      },
    ],
    name: "transferInternalCoins",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISafeManager__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeManagerInterface {
    return new utils.Interface(_abi) as ISafeManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeManager {
    return new Contract(address, _abi, signerOrProvider) as ISafeManager;
  }
}
