/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common.js";
import type { MinHeap, MinHeapInterface } from "../MinHeap.js";

const _abi = [
  {
    inputs: [],
    name: "HEAP_EMPTY",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220c0b6eb07cfc0da25d985164857a00a71214013077260d44a01b1b327724ca84e64736f6c634300080a0033";

type MinHeapConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MinHeapConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MinHeap__factory extends ContractFactory {
  constructor(...args: MinHeapConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MinHeap> {
    return super.deploy(overrides || {}) as Promise<MinHeap>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MinHeap {
    return super.attach(address) as MinHeap;
  }
  override connect(signer: Signer): MinHeap__factory {
    return super.connect(signer) as MinHeap__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MinHeapInterface {
    return new utils.Interface(_abi) as MinHeapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MinHeap {
    return new Contract(address, _abi, signerOrProvider) as MinHeap;
  }
}
