version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  install:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: yarn install:foundry
  setup-foundry:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: source /home/circleci/.bashrc
      - run: yarn setup:foundry
  test:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn test:contracts
      - run: yarn test:client
  build:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn build

workflows:
  build:
    jobs:
      - install
      - setup-foundry:
          requires:
            - install
      - test:
          requires:
            - setup-foundry
      - build:
          requires:
            - test
