version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
  test:
    steps:
      - yarn test:contracts
      - yarn test:client

  build:
    steps:
      - yarn build

workflows:
  test:
    jobs:
      - install-node-example
      - test
      - build
