version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  install:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run:
          name: Setup Foundry
          command: |
            yarn setup:foundry
            source /home/circleci/.bashrc
            yarn install:foundry
  test:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn test:contracts
      - run: yarn test:client
  build:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn build

workflows:
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
