version: "2.1"
orbs:
  node: circleci/node@5.0.0
jobs:
  build-and-test:
    docker:
      - image: "cimg/python:3.10.6"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run:
          name: Setup Vyper
          shell: /bin/bash
          command: |
            pip install vyper
            export PATH=/home/cicleci/.local/bin:$PATH
            vyper --version
      - run:
          name: Setup Foundry
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            yarn install:foundryup
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn install:foundry
      - run:
          name: Build Project
          shell: /bin/bash
          command: |
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn install:dependencies
            yarn build
      - run:
          name: Check Formatting
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn formatting:check
      - run:
          name: Check Linting Errors in Contracts
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            yarn lint:contracts
      - run:
          name: Check Linting Errors in Clients
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            yarn lint:clients
      - run:
          name: Test Contracts
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn test:contracts
      - run:
          name: Test Clients
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn test:clients
  publish:
    docker:
      - image: "cimg/python:3.10.6"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Setup Vyper
          shell: /bin/bash
          command: |
            pip install vyper
            export PATH=/home/cicleci/.local/bin:$PATH
            vyper --version
      - run:
          name: Setup Foundry
          shell: /bin/bash
          command: |
            yarn config set script-shell /bin/bash
            yarn install:foundryup
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn install:foundry
      - run:
          name: Build Project
          shell: /bin/bash
          command: |
            export PATH=/home/circleci/.foundry/bin:$PATH
            yarn install:dependencies
            yarn build
      - run:
          name: Publish
          shell: /bin/bash
          command: |
            yarn publish --access public

workflows:
  install:
    jobs:
      - build-and-test
  deploy:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
