version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  install:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run:
          shell: /bin/bash
          command: yarn install:foundry
      - run:
          name: Setup Foundry
          shell: /bin/bash
          command: |
            export PATH=/home/circleci/.foundry/bin:$PATH
            export PATH=/home/circleci/.forge/bin:$PATH
            yarn setup:foundry
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run:
          name: Test
          shell: /bin/bash
          command: |
            export PATH=/home/circleci/.foundry/bin:$PATH
            export PATH=/home/circleci/.forge/bin:$PATH
            yarn compile:typechain
            yarn test:contracts
            yarn test:client
  build:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            export PATH=/home/circleci/.foundry/bin:$PATH
            export PATH=/home/circleci/.forge/bin:$PATH
            yarn build

workflows:
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
