version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  install:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: sudo apt install bash
      - run: node --version
      - run:
          shell: bin/bash
          command: yarn install:foundry
      - run:
          name: Setup Foundry varrs
          shell: bin/bash
          command: |
            echo 'export PATH=/home/circleci/.foundry/bin:$PATH' >> $BASH_ENV
            echo 'export PATH=/home/circleci/.forge/bin:$PATH' >> $BASH_ENV
      - run:
          shell: /bin/bash
          command: yarn setup:foundry
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn test:contracts
      - run: yarn test:client
  build:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - run: yarn build

workflows:
  build:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - test
