version: '2.1'
orbs:
  node: circleci/node@5.0
jobs:
  test:
    docker:
      - image: 'aztecprotocol/build-image'
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run: node --version
      - run: yarn setup
      - run: yarn test:contracts
      - run: yarn test:client
      - run: yarn build

workflows:
  test:
    jobs:
      - test
