/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ElementTestInterface extends utils.Interface {
  contractName: "ElementTest";
  functions: {
    "IS_TEST()": FunctionFragment;
    "compareStrings(string,string)": FunctionFragment;
    "failed()": FunctionFragment;
    "hashAssetAndExpiry(address,uint64)": FunctionFragment;
    "setUp()": FunctionFragment;
    "testCanConfigureMultiplePools()": FunctionFragment;
    "testCanConfigurePool()": FunctionFragment;
    "testCanConfigureSamePoolMultipleTimes()": FunctionFragment;
    "testCanConvert()": FunctionFragment;
    "testCanFinaliseAllInteractionsOnConvert()": FunctionFragment;
    "testCanFinaliseDaiApr22()": FunctionFragment;
    "testCanFinaliseDaiJan22()": FunctionFragment;
    "testCanProcessAllExpiries()": FunctionFragment;
    "testCanRegisterAllPools()": FunctionFragment;
    "testMultipleInteractionsAreFinalisedOnConvert()": FunctionFragment;
    "testMultipleInteractionsFailToFinaliseIfInsufficientBalance()": FunctionFragment;
    "testRejectAlreadyFinalised()": FunctionFragment;
    "testRejectConvertDuplicateNonce()": FunctionFragment;
    "testRejectFinaliseInvalidCaller()": FunctionFragment;
    "testRejectFinaliseNotReady()": FunctionFragment;
    "testRejectFinaliseUnknownNonce()": FunctionFragment;
    "testRejectsIncorrectWrappedPositionForPool()": FunctionFragment;
    "testRejectsInvalidPoolAddress()": FunctionFragment;
    "testRejectsInvalidWrappedPosition()": FunctionFragment;
    "testRejectsWrongExpiryForPool()": FunctionFragment;
    "testShouldRejectEthAsset()": FunctionFragment;
    "testShouldRejectInconsistentAssetIds()": FunctionFragment;
    "testShouldRejectInconsistentPool()": FunctionFragment;
    "testShouldRejectNonRollupCaller()": FunctionFragment;
    "testShouldRejectUnusedAsset()": FunctionFragment;
    "testShouldRejectVirtualAsset()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "compareStrings",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hashAssetAndExpiry",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "testCanConfigureMultiplePools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanConfigurePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanConfigureSamePoolMultipleTimes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanConvert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanFinaliseAllInteractionsOnConvert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanFinaliseDaiApr22",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanFinaliseDaiJan22",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanProcessAllExpiries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanRegisterAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testMultipleInteractionsAreFinalisedOnConvert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testMultipleInteractionsFailToFinaliseIfInsufficientBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectAlreadyFinalised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectConvertDuplicateNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectFinaliseInvalidCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectFinaliseNotReady",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectFinaliseUnknownNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectsIncorrectWrappedPositionForPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectsInvalidPoolAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectsInvalidWrappedPosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRejectsWrongExpiryForPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectEthAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectInconsistentAssetIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectInconsistentPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectNonRollupCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectUnusedAsset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testShouldRejectVirtualAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "compareStrings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashAssetAndExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testCanConfigureMultiplePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanConfigurePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanConfigureSamePoolMultipleTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanConvert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanFinaliseAllInteractionsOnConvert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanFinaliseDaiApr22",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanFinaliseDaiJan22",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanProcessAllExpiries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanRegisterAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testMultipleInteractionsAreFinalisedOnConvert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testMultipleInteractionsFailToFinaliseIfInsufficientBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectAlreadyFinalised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectConvertDuplicateNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectFinaliseInvalidCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectFinaliseNotReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectFinaliseUnknownNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectsIncorrectWrappedPositionForPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectsInvalidPoolAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectsInvalidWrappedPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testRejectsWrongExpiryForPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectEthAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectInconsistentAssetIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectInconsistentPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectNonRollupCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectUnusedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testShouldRejectVirtualAsset",
    data: BytesLike
  ): Result;

  events: {
    "Convert(uint256,uint256)": EventFragment;
    "Finalise(uint256,bool,string)": EventFragment;
    "PoolAdded(address,address,uint64)": EventFragment;
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Convert"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Finalise"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export type ConvertEvent = TypedEvent<
  [BigNumber, BigNumber],
  { nonce: BigNumber; totalInputValue: BigNumber }
>;

export type ConvertEventFilter = TypedEventFilter<ConvertEvent>;

export type FinaliseEvent = TypedEvent<
  [BigNumber, boolean, string],
  { nonce: BigNumber; success: boolean; message: string }
>;

export type FinaliseEventFilter = TypedEventFilter<FinaliseEvent>;

export type PoolAddedEvent = TypedEvent<
  [string, string, BigNumber],
  { poolAddress: string; wrappedPositionAddress: string; expiry: BigNumber }
>;

export type PoolAddedEventFilter = TypedEventFilter<PoolAddedEvent>;

export type logEvent = TypedEvent<[string], { arg0: string }>;

export type logEventFilter = TypedEventFilter<logEvent>;

export type log_addressEvent = TypedEvent<[string], { arg0: string }>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export type log_bytesEvent = TypedEvent<[string], { arg0: string }>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export type log_bytes32Event = TypedEvent<[string], { arg0: string }>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export type log_intEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export type log_named_addressEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export type log_named_bytesEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export type log_named_bytes32Event = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { key: string; val: BigNumber; decimals: BigNumber }
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { key: string; val: BigNumber; decimals: BigNumber }
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  { key: string; val: BigNumber }
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export type log_named_stringEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  { key: string; val: BigNumber }
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export type log_stringEvent = TypedEvent<[string], { arg0: string }>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export type log_uintEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export type logsEvent = TypedEvent<[string], { arg0: string }>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface ElementTest extends BaseContract {
  contractName: "ElementTest";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ElementTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    hashAssetAndExpiry(
      asset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanConfigureMultiplePools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanConfigurePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanConfigureSamePoolMultipleTimes(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanFinaliseAllInteractionsOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanFinaliseDaiApr22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanFinaliseDaiJan22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanProcessAllExpiries(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanRegisterAllPools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testMultipleInteractionsAreFinalisedOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testMultipleInteractionsFailToFinaliseIfInsufficientBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectAlreadyFinalised(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectConvertDuplicateNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectFinaliseInvalidCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectFinaliseNotReady(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectFinaliseUnknownNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectsIncorrectWrappedPositionForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectsInvalidPoolAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectsInvalidWrappedPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testRejectsWrongExpiryForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectEthAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectInconsistentAssetIds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectInconsistentPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectNonRollupCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectUnusedAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testShouldRejectVirtualAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  compareStrings(
    a: string,
    b: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  hashAssetAndExpiry(
    asset: string,
    expiry: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setUp(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanConfigureMultiplePools(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanConfigurePool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanConfigureSamePoolMultipleTimes(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanConvert(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanFinaliseAllInteractionsOnConvert(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanFinaliseDaiApr22(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanFinaliseDaiJan22(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanProcessAllExpiries(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanRegisterAllPools(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testMultipleInteractionsAreFinalisedOnConvert(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testMultipleInteractionsFailToFinaliseIfInsufficientBalance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectAlreadyFinalised(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectConvertDuplicateNonce(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectFinaliseInvalidCaller(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectFinaliseNotReady(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectFinaliseUnknownNonce(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectsIncorrectWrappedPositionForPool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectsInvalidPoolAddress(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectsInvalidWrappedPosition(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testRejectsWrongExpiryForPool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectEthAsset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectInconsistentAssetIds(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectInconsistentPool(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectNonRollupCaller(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectUnusedAsset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testShouldRejectVirtualAsset(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    hashAssetAndExpiry(
      asset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setUp(overrides?: CallOverrides): Promise<void>;

    testCanConfigureMultiplePools(overrides?: CallOverrides): Promise<void>;

    testCanConfigurePool(overrides?: CallOverrides): Promise<void>;

    testCanConfigureSamePoolMultipleTimes(
      overrides?: CallOverrides
    ): Promise<void>;

    testCanConvert(overrides?: CallOverrides): Promise<void>;

    testCanFinaliseAllInteractionsOnConvert(
      overrides?: CallOverrides
    ): Promise<void>;

    testCanFinaliseDaiApr22(overrides?: CallOverrides): Promise<void>;

    testCanFinaliseDaiJan22(overrides?: CallOverrides): Promise<void>;

    testCanProcessAllExpiries(overrides?: CallOverrides): Promise<void>;

    testCanRegisterAllPools(overrides?: CallOverrides): Promise<void>;

    testMultipleInteractionsAreFinalisedOnConvert(
      overrides?: CallOverrides
    ): Promise<void>;

    testMultipleInteractionsFailToFinaliseIfInsufficientBalance(
      overrides?: CallOverrides
    ): Promise<void>;

    testRejectAlreadyFinalised(overrides?: CallOverrides): Promise<void>;

    testRejectConvertDuplicateNonce(overrides?: CallOverrides): Promise<void>;

    testRejectFinaliseInvalidCaller(overrides?: CallOverrides): Promise<void>;

    testRejectFinaliseNotReady(overrides?: CallOverrides): Promise<void>;

    testRejectFinaliseUnknownNonce(overrides?: CallOverrides): Promise<void>;

    testRejectsIncorrectWrappedPositionForPool(
      overrides?: CallOverrides
    ): Promise<void>;

    testRejectsInvalidPoolAddress(overrides?: CallOverrides): Promise<void>;

    testRejectsInvalidWrappedPosition(overrides?: CallOverrides): Promise<void>;

    testRejectsWrongExpiryForPool(overrides?: CallOverrides): Promise<void>;

    testShouldRejectEthAsset(overrides?: CallOverrides): Promise<void>;

    testShouldRejectInconsistentAssetIds(
      overrides?: CallOverrides
    ): Promise<void>;

    testShouldRejectInconsistentPool(overrides?: CallOverrides): Promise<void>;

    testShouldRejectNonRollupCaller(overrides?: CallOverrides): Promise<void>;

    testShouldRejectUnusedAsset(overrides?: CallOverrides): Promise<void>;

    testShouldRejectVirtualAsset(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Convert(uint256,uint256)"(
      nonce?: BigNumberish | null,
      totalInputValue?: null
    ): ConvertEventFilter;
    Convert(
      nonce?: BigNumberish | null,
      totalInputValue?: null
    ): ConvertEventFilter;

    "Finalise(uint256,bool,string)"(
      nonce?: BigNumberish | null,
      success?: null,
      message?: null
    ): FinaliseEventFilter;
    Finalise(
      nonce?: BigNumberish | null,
      success?: null,
      message?: null
    ): FinaliseEventFilter;

    "PoolAdded(address,address,uint64)"(
      poolAddress?: null,
      wrappedPositionAddress?: null,
      expiry?: null
    ): PoolAddedEventFilter;
    PoolAdded(
      poolAddress?: null,
      wrappedPositionAddress?: null,
      expiry?: null
    ): PoolAddedEventFilter;

    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    hashAssetAndExpiry(
      asset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanConfigureMultiplePools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanConfigurePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanConfigureSamePoolMultipleTimes(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanFinaliseAllInteractionsOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanFinaliseDaiApr22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanFinaliseDaiJan22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanProcessAllExpiries(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanRegisterAllPools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testMultipleInteractionsAreFinalisedOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testMultipleInteractionsFailToFinaliseIfInsufficientBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectAlreadyFinalised(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectConvertDuplicateNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectFinaliseInvalidCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectFinaliseNotReady(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectFinaliseUnknownNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectsIncorrectWrappedPositionForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectsInvalidPoolAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectsInvalidWrappedPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testRejectsWrongExpiryForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectEthAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectInconsistentAssetIds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectInconsistentPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectNonRollupCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectUnusedAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testShouldRejectVirtualAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    compareStrings(
      a: string,
      b: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hashAssetAndExpiry(
      asset: string,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanConfigureMultiplePools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanConfigurePool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanConfigureSamePoolMultipleTimes(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanFinaliseAllInteractionsOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanFinaliseDaiApr22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanFinaliseDaiJan22(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanProcessAllExpiries(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanRegisterAllPools(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testMultipleInteractionsAreFinalisedOnConvert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testMultipleInteractionsFailToFinaliseIfInsufficientBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectAlreadyFinalised(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectConvertDuplicateNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectFinaliseInvalidCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectFinaliseNotReady(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectFinaliseUnknownNonce(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectsIncorrectWrappedPositionForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectsInvalidPoolAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectsInvalidWrappedPosition(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testRejectsWrongExpiryForPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectEthAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectInconsistentAssetIds(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectInconsistentPool(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectNonRollupCaller(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectUnusedAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testShouldRejectVirtualAsset(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
